image: mcr.microsoft.com/dotnet/sdk:7.0

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: '*/*/'

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push
  
stages:
  - build
  - test

build:
  tags:
    - docker
  stage: build
  script: 
    - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'
    - 'dotnet build --no-restore'

test-code-job1:
  tags:
    - docker
  stage: test
  script:
    - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'
    - 'dotnet test --no-restore --logger "junit;LogFilePath=testresults.xml"'
  artifacts:
    when: always
    paths:
      - 'HamsterIoHTests/testresults.xml'
    reports:
      junit: 'HamsterIoHTests/testresults.xml'
